services:
  - type: web
    name: reel-tracker-frontend
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://reel-tracker-backend.onrender.com
      - key: REACT_APP_OMDB_KEY
        sync: false