services:
  - type: web
    name: reel-tracker-backend
    runtime: node
    repo: https://github.com/Utkarsh6358/reel-show-tracker
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OMDB_KEY
        sync: false
      - key: SHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false

  - type: static
    name: reel-tracker-frontend
    repo: https://github.com/Utkarsh6358/reel-show-tracker
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://reel-tracker-backend.onrender.com
      - key: REACT_APP_OMDB_KEY
        sync: false
