services:
  - type: web
    name: reel-tracker-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OMDB_KEY
        sync: false
      - key: SHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false